version: "2"
services:
  jobmanager:
    image: flink:1.5-hadoop28
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      AWS_ACCESS_KEY_ID:
      AWS_SECURITY_TOKEN:
      AWS_SESSION_TOKEN:
      AWS_SECRET_ACCESS_KEY:

  taskmanager:
    image: flink:1.5-hadoop28
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      AWS_ACCESS_KEY_ID:
      AWS_SECURITY_TOKEN:
      AWS_SESSION_TOKEN:
      AWS_SECRET_ACCESS_KEY:
